# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=300)),
                ('image_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.DateTimeField()),
                ('query', models.CharField(max_length=500)),
                ('task_id', models.CharField(blank=True, editable=False, max_length=50)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
            ],
        ),
    ]
