# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.DateTimeField()),
                ('query', models.CharField(max_length=500)),
                ('task_id', models.CharField(blank=True, editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
            ],
        ),
        migrations.RemoveField(
            model_name='notificationstate',
            name='notification',
        ),
        migrations.DeleteModel(
            name='NotificationState',
        ),
    ]
